// Generated by drizzle-kit introspect against a copy of bridge.db.
// Hand-patched (T3) for: (1) boolean-as-INTEGER coercion using
// `integer({ mode: "boolean" })`, (2) the broken `user_id` default that
// drizzle-kit emitted as a string literal `"sql\`(NULL)\`"`. Re-running
// `bun run db:introspect` will regenerate this file — diff manually before
// commit (see docs/web-dashboard/tasks/phase-0/T03-review.md).

import { sqliteTable, AnySQLiteColumn, primaryKey, text, numeric, integer, index, foreignKey, real } from "drizzle-orm/sqlite-core"
import { sql } from "drizzle-orm"

export const agents = sqliteTable("agents", {
	name: text().notNull(),
	projectDir: text("project_dir").notNull(),
	sessionId: text("session_id").notNull(),
	agentFile: text("agent_file").notNull(),
	purpose: text(),
	state: text().default("created"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	lastTaskAt: numeric("last_task_at"),
	totalTasks: integer("total_tasks").default(0),
	model: text().default("sonnet"),
},
(table) => [
	primaryKey({ columns: [table.name, table.projectDir], name: "agents_name_project_dir_pk"})
]);

export const tasks = sqliteTable("tasks", {
	id: integer().primaryKey({ autoIncrement: true }),
	sessionId: text("session_id").notNull().references(() => agents.sessionId, { onDelete: "cascade" } ),
	prompt: text().notNull(),
	status: text().default("pending"),
	pid: integer(),
	resultFile: text("result_file"),
	resultSummary: text("result_summary"),
	costUsd: real("cost_usd"),
	durationMs: integer("duration_ms"),
	numTurns: integer("num_turns"),
	exitCode: integer("exit_code"),
	errorMessage: text("error_message"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	startedAt: numeric("started_at"),
	completedAt: numeric("completed_at"),
	reported: integer({ mode: "boolean" }).default(false),
	position: integer(),
	model: text(),
	taskType: text("task_type").default("standard"),
	parentTaskId: integer("parent_task_id"),
	channel: text().default("cli"),
	channelChatId: text("channel_chat_id"),
	channelMessageId: text("channel_message_id"),
	// drizzle-kit introspect emitted `default("sql`(NULL)`")` here — patched
	// to a real NULL default. The underlying SQL is `DEFAULT NULL`, equivalent
	// to no default for a nullable column.
	userId: text("user_id"),
},
(table) => [
	index("idx_tasks_parent").on(table.parentTaskId),
	index("idx_tasks_unreported").on(table.status, table.reported),
	index("idx_tasks_session").on(table.sessionId),
	index("idx_tasks_status").on(table.status),
	foreignKey(() => ({
			columns: [table.parentTaskId],
			foreignColumns: [table.id],
			name: "tasks_parent_task_id_tasks_id_fk"
		})),
]);

export const permissions = sqliteTable("permissions", {
	id: text().primaryKey(),
	sessionId: text("session_id").notNull(),
	toolName: text("tool_name").notNull(),
	command: text(),
	description: text(),
	status: text().default("pending"),
	response: text(),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	respondedAt: numeric("responded_at"),
	timeoutSeconds: integer("timeout_seconds").default(300),
},
(table) => [
	index("idx_permissions_status").on(table.status),
]);

export const teams = sqliteTable("teams", {
	name: text().primaryKey(),
	leadAgent: text("lead_agent").notNull(),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
});

export const teamMembers = sqliteTable("team_members", {
	teamName: text("team_name").notNull().references(() => teams.name, { onDelete: "cascade" } ),
	agentName: text("agent_name").notNull(),
},
(table) => [
	primaryKey({ columns: [table.teamName, table.agentName], name: "team_members_team_name_agent_name_pk"})
]);

export const notifications = sqliteTable("notifications", {
	id: integer().primaryKey({ autoIncrement: true }),
	taskId: integer("task_id").references(() => tasks.id),
	channel: text().notNull(),
	chatId: text("chat_id").notNull(),
	message: text().notNull(),
	status: text().default("pending"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	sentAt: numeric("sent_at"),
},
(table) => [
	index("idx_notifications_status").on(table.status),
]);

export const loops = sqliteTable("loops", {
	loopId: text("loop_id").primaryKey(),
	agent: text().notNull(),
	project: text().notNull(),
	goal: text().notNull(),
	doneWhen: text("done_when").notNull(),
	loopType: text("loop_type").default("bridge").notNull(),
	status: text().default("running").notNull(),
	maxIterations: integer("max_iterations").default(10).notNull(),
	maxConsecutiveFailures: integer("max_consecutive_failures").default(3).notNull(),
	currentIteration: integer("current_iteration").default(0).notNull(),
	consecutiveFailures: integer("consecutive_failures").default(0).notNull(),
	totalCostUsd: real("total_cost_usd").notNull(),
	maxCostUsd: real("max_cost_usd"),
	pendingApproval: integer("pending_approval", { mode: "boolean" }).default(false).notNull(),
	startedAt: text("started_at").notNull(),
	finishedAt: text("finished_at"),
	finishReason: text("finish_reason"),
	currentTaskId: text("current_task_id"),
	channel: text(),
	channelChatId: text("channel_chat_id"),
	userId: text("user_id"),
	plan: text(),
	planEnabled: integer("plan_enabled", { mode: "boolean" }).default(false).notNull(),
	passThreshold: integer("pass_threshold").default(1).notNull(),
	consecutivePasses: integer("consecutive_passes").default(0).notNull(),
},
(table) => [
	index("idx_loops_agent").on(table.agent),
	index("idx_loops_status").on(table.status),
]);

export const loopIterations = sqliteTable("loop_iterations", {
	id: integer().primaryKey({ autoIncrement: true }),
	loopId: text("loop_id").notNull(),
	iterationNum: integer("iteration_num").notNull(),
	taskId: text("task_id"),
	prompt: text(),
	resultSummary: text("result_summary"),
	doneCheckPassed: integer("done_check_passed", { mode: "boolean" }).default(false).notNull(),
	costUsd: real("cost_usd").notNull(),
	startedAt: text("started_at").notNull(),
	finishedAt: text("finished_at"),
	status: text().default("running").notNull(),
},
(table) => [
	index("idx_loop_iterations_loop").on(table.loopId),
]);

// ─────────────────────────────────────────────────────────────────────────────
// DASHBOARD-OWNED tables.
// These are NOT vendored from the daemon's `bridge.db` schema. They are
// created and maintained by `src/server/migrate.ts` and live alongside the
// daemon-owned tables in the same SQLite file (per v1 ARCHITECTURE.md §3).
// Re-running `bun run db:introspect` will surface them as drift — keep the
// generated diff but do NOT delete this block.
// ─────────────────────────────────────────────────────────────────────────────

// P4-T01 — `users` table. Dashboard-owned. Created by migration
// `0002_users.sql`. `id` is a UUID for magic-link-created rows or the
// literal `"owner"` for the env-password fallback identity backfilled
// on first use (see `src/server/routers/auth.ts`). `email_lower` is a
// generated column used for case-insensitive uniqueness.
export const users = sqliteTable("users", {
	id: text().primaryKey(),
	email: text().notNull(),
	emailLower: text("email_lower"),
	role: text().notNull().default("member"),
	displayName: text("display_name"),
	createdAt: integer("created_at").notNull(),
	lastLoginAt: integer("last_login_at"),
	revokedAt: integer("revoked_at"),
},
(table) => [
	index("idx_users_email_lower").on(table.emailLower),
	index("idx_users_revoked_at").on(table.revokedAt),
]);

// P4-T01 — `magic_links` table. Dashboard-owned. Created by migration
// `0003_magic_links.sql`. The plaintext token is never stored — only
// `token_hash` (SHA-256 of the random 32-byte URL-safe token).
// `consumed_at` is the single-use guard.
export const magicLinks = sqliteTable("magic_links", {
	tokenHash: text("token_hash").primaryKey(),
	email: text().notNull(),
	emailLower: text("email_lower"),
	createdAt: integer("created_at").notNull(),
	expiresAt: integer("expires_at").notNull(),
	consumedAt: integer("consumed_at"),
	requestIpHash: text("request_ip_hash"),
},
(table) => [
	index("idx_magic_links_expires_at").on(table.expiresAt),
	index("idx_magic_links_email_lower").on(table.emailLower),
]);

export const auditLog = sqliteTable("audit_log", {
	id: integer().primaryKey({ autoIncrement: true }),
	userId: text("user_id"),
	action: text().notNull(),
	resourceType: text("resource_type").notNull(),
	resourceId: text("resource_id"),
	payloadJson: text("payload_json"),
	ipHash: text("ip_hash"),
	userAgent: text("user_agent"),
	requestId: text("request_id"),
	createdAt: integer("created_at").notNull(),
},
(table) => [
	index("idx_audit_log_created_at").on(table.createdAt),
	index("idx_audit_log_user_created_at").on(table.userId, table.createdAt),
]);

// ─────────────────────────────────────────────────────────────────────────────

export const schedules = sqliteTable("schedules", {
	id: integer().primaryKey({ autoIncrement: true }),
	name: text().notNull(),
	agentName: text("agent_name").notNull(),
	prompt: text().notNull(),
	intervalMinutes: integer("interval_minutes"),
	cronExpr: text("cron_expr"),
	runOnce: integer("run_once", { mode: "boolean" }).default(false),
	enabled: integer({ mode: "boolean" }).default(true),
	runCount: integer("run_count").default(0),
	consecutiveErrors: integer("consecutive_errors").default(0),
	lastRunAt: numeric("last_run_at"),
	nextRunAt: numeric("next_run_at"),
	lastError: text("last_error"),
	channel: text().default("cli"),
	channelChatId: text("channel_chat_id"),
	userId: text("user_id"),
	createdAt: numeric("created_at").default(sql`(CURRENT_TIMESTAMP)`),
	updatedAt: numeric("updated_at").default(sql`(CURRENT_TIMESTAMP)`),
},
(table) => [
	index("idx_schedules_next_run").on(table.nextRunAt, table.enabled),
]);

